import type { Product, Category } from "./types"

export const mockCategories: Category[] = [
  {
    id: "1",
    name: "Bebidas",
    description: "Gaseosas, jugos, aguas",
    icon: "🥤",
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Snacks",
    description: "Papas fritas, galletitas, golosinas",
    icon: "🍿",
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Cigarrillos",
    description: "Cigarrillos y tabacos",
    icon: "🚬",
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Almacén",
    description: "Productos de almacén general",
    icon: "🏪",
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Lácteos",
    description: "Leche, yogures, quesos",
    icon: "🥛",
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Congelados",
    description: "Helados y productos congelados",
    icon: "🍦",
    active: true,
    created_at: new Date().toISOString(),
  },
]

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Coca Cola 500ml",
    description: "Gaseosa Coca Cola 500ml",
    sku: "CC500",
    barcode: "7790001001",
    category_id: "1",
    price: 1200,
    cost: 800,
    stock: 50,
    min_stock: 10,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Pepsi 500ml",
    description: "Gaseosa Pepsi 500ml",
    sku: "PP500",
    barcode: "7790001002",
    category_id: "1",
    price: 1100,
    cost: 750,
    stock: 45,
    min_stock: 10,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Lays Clásicas",
    description: "Papas fritas Lays sabor clásico",
    sku: "LAYS001",
    barcode: "7790002001",
    category_id: "2",
    price: 1500,
    cost: 1000,
    stock: 30,
    min_stock: 8,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Oreo Original",
    description: "Galletitas Oreo pack original",
    sku: "OREO001",
    barcode: "7790002002",
    category_id: "2",
    price: 2000,
    cost: 1400,
    stock: 25,
    min_stock: 5,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Marlboro Box",
    description: "Cigarrillos Marlboro Box 20u",
    sku: "MARL001",
    barcode: "7790003001",
    category_id: "3",
    price: 3500,
    cost: 2800,
    stock: 100,
    min_stock: 20,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Sprite 500ml",
    description: "Gaseosa Sprite Lima-Limón 500ml",
    sku: "SPR500",
    barcode: "7790001003",
    category_id: "1",
    price: 1150,
    cost: 780,
    stock: 40,
    min_stock: 10,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
